project:
  type: website
  output-dir: docs
  render:
    - "00_about.qmd"
    - "FIT5306/"
    - "RGV410046/RGV410046_00_ABOUT.qmd"

comments:
  hypothesis: 
    theme: clean
  
theme:
  light: flatly
  dark: darkly

website:
  repo-url: https://github.com/TiagoOlivoto/classes
  repo-actions: [edit, issue]
  search:
    location: sidebar
  title: "Aulas"
  crossref:
    fig-title: Fig     # (default is "Figure")
    tbl-title: Tbl     # (default is "Table")
    title-delim: —     # (default is ":")
  page-layout: custom
  page-footer:
    border: true
    background: light
    left: "Material de apoio à disciplinas "
    right: "Prof. Dr. Tiago Olivoto FIT/CCA/UFSC "
  page-navigation: true
  navbar:
    background: "#0759e8"
    search: true
    left:
      - text: "About"
        file: 00_about.qmd
        icon: fa fa-home
      - text: "Bioestatística"
        file: FIT5306/FIT5306_00_ABOUT.qmd
      - text: "Introdução ao R"
        file: RGV410046/RGV410046_00_ABOUT.qmd


    right:
      - icon: "fab fa-researchgate fa"
        href: https://www.researchgate.net/profile/Tiago_Olivoto
      - icon: bi bi-github
        href: https://github.com/TiagoOlivoto/classes
      - icon: bi bi-twitter
        href: https://twitter.com/tolivoto
      - icon: "fab fa-mendeley fa"
        href: https://www.mendeley.com/profiles/tiago-olivoto/


  sidebar:
    - title: "Bioestatística"
      style: "docked"
      background: light
      contents:
        - FIT5306/FIT5306_00_ABOUT.qmd
        - FIT5306/FIT5306_01_DESC.qmd
        - FIT5306/FIT5306_02_FREQ.qmd
        - FIT5306/FIT5306_03_DIST_DISCRET.qmd
        - FIT5306/FIT5306_04_DIST_CONT.qmd
        - FIT5306/FIT5306_05_DATAVIZ.qmd
        - FIT5306/FIT5306_06_AMOSTRAGEM.qmd
        - FIT5306/FIT5306_07_DELN.qmd
        - FIT5306/FIT5306_08_DIC.qmd
        - FIT5306/FIT5306_09_DBC.qmd
        - FIT5306/FIT5306_10_FAT.qmd
        - FIT5306/FIT5306_11_REG.qmd
    - title: "Intro R"
      style: "docked"
      background: light
      contents:
        - RGV410046/RGV410046_00_ABOUT.qmd


format:
  html:
    theme: 
       light: journal
       dark: darkly
    toc: true
    toc-title: "Nesta página"
    toc-depth: 4
    number-sections: false
    number-depth: 3
    smooth-scroll: true
    code-fold: false
    code-summary: "Mostrar script"
    code-tools: true
    code-block-bg: "#f5f2f2"
    highlight-style: tango
    code-block-border-left: "#31BAE9"
    
execute:
  collapse: true
  out-width: "100%"
